groups:
  - name: ui
    description: UI translations
  - name: reports
    description: Translations of report title and descriptions
  - name: errors
    description: Translations of errors
languages:
  - name: English
    locale: en
  - name: Français
    locale: fr
  - name: Portuguese
    locale: pt
translations:
################################################################################
# ENGLISH translations
################################################################################
  - not_in_group: [errors]
    locale: en
    keys:
      - desc: Short description
  - group:
    locale: en
    keys:
      - generic_key : A key without a group
  - group: ui
    locale: en
    keys:
      - welc: Welcome
      - user_details: User Details Section
      - add_attachment_description: Add attachment description
  - group: errors
    locale: en
    keys:
      - warn: Warning
      - unexpected_error: An unexpected error has occurred.
      - login_failure: Login failed due to invalid credentials, please try again
        forceUpdate: true
################################################################################
# FRENCH translations
################################################################################
  - group: ui
    locale: fr
    keys:
      - add_attachment_description: Description de la pièce jointe
  - group: reports
    locale: fr
    keys:
      - reports_dir: Répertoire des rapports
  - group: errors
    locale: fr
    keys:
      - warn: Attention
      - unexpected_error: Une erreur imprévue s'est produite
      - login_failure: La connexion a échoué en raison d'informations d'identification non valides
  ################################################################################
  # PORTUGUESE translations
  ################################################################################
  - group: ui
    locale: pt
    keys:
      - add_attachment_description: adicionar descrição do anexo
  - group: errors
    locale: pt
    keys:
      - warn: Aviso
      - unexpected_error: Ocorreu um erro inesperado
      - login_failure: Falha no login devido a credenciais inválidas
        forceDelete: true




















